networks:
  tifa:
    external: true

services:
  qbee:
    image: qbee
    container_name: qbee
    entrypoint: /app/entrypoint.sh
    environment:
      EMAIL: ${EMAIL}
    hostname: ${HOSTNAME}
    labels:
      traefik.enable: true
      traefik.http.routers.qbee.rule: Host(`${HOSTNAME}`)
      traefik.http.routers.qbee.entrypoints: websecure
      traefik.http.routers.qbee.tls.certresolver: letsencrypt
      traefik.http.services.qbee.loadbalancer.server.port: 80
    networks:
      - tifa
    restart: always

volumes:
  tifa_mysql:
    external: true
